"""RepositoryProvider protocol — the seam between Scout's agent and any backend.

Implementations: GitHubProvider (real GitHub via PyGithub) and GitHubSimulator
(in-memory). Both must satisfy this protocol; the agent only sees the interface.
"""
from __future__ import annotations

from typing import Protocol


class RepositoryProvider(Protocol):
    # ---- read ----
    def get_issue_data(self, issue_number: int) -> dict: ...
    def search_issues(self, query: str, max_results: int) -> list[dict]: ...
    def list_directory(self, path: str) -> list[str]: ...
    def get_file_contents(self, path: str) -> str: ...
    def fetch_readme(self) -> str | None: ...

    # ---- write ----
    def add_reaction(self, issue_number: int, reaction: str) -> None: ...
    def apply_label(self, issue_number: int, label_name: str) -> str: ...
    def post_comment(self, issue_number: int, body: str) -> None: ...
